name: Python Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install apache-airflow
          pip install pytest-helpers-namespace

      - name: Run tests
        run: pytest tests/
